
export const SCREENS = {
    LOGIN: 'LOGIN',
    ONBOARDING: 'ONBOARDING',
    HOME: 'HOME',
    DISCOVER: 'DISCOVER',
    PORTFOLIO: 'PORTFOLIO',
    AI_ASSISTANT: 'AI_ASSISTANT',
    PROFILE: 'PROFILE',
    STOCK_DETAIL: 'STOCK_DETAIL',
    AI_INSIGHTS: 'AI_INSIGHTS',
    RECOMMENDED_STOCKS: 'RECOMMENDED_STOCKS',
    REGISTRATION: 'REGISTRATION',
    KYC_PAN_AADHAAR: 'KYC_PAN_AADHAAR',
    KYC_DIGILOCKER: 'KYC_DIGILOCKER',
    KYC_SUCCESS: 'KYC_SUCCESS',
} as const;